version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: gym_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 250498La
      MYSQL_DATABASE: GYM
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
